spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Taipei
    username: root
    password: 123456
  messages:
    encoding=UTF-8
server:
  port: 8081

